spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    url: jdbc:mysql://localhost:33306/share_user

server:
  port: 8081

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true