server:
  port: 8095
spring:
  data:
    mongodb:
      database: share_resource
      authentication-database: admin
      host: localhost
      port: 27017
      username: root
      password: root